//#include<iostream>
////#include<vcruntime_exception.h>
//
//int main()
//{
//	while (true) {
//		int n;
//		std::cout << "enter number: ";
//		std::cin >> n;
//
//		try {
//
//			int res = 11;
//
//			std::cout << "in try block ans: " << res / n << std::endl;
//
//		}
//		catch (...)
//		{
//			std::cout << "in catch block\n" << std::endl;
//		}
//	}
//}